import { createHash } from "node:crypto";
import { readdirSync, statSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { join, posix } from "node:path";

// Astro-6-native PWA integration. On `astro:build:done` it builds a precache
// manifest from the emitted output, hashes it into a cache version, and writes
// `sw.js` into the output dir. No third-party PWA dependency — see
// docs/superpowers/specs/2026-06-19-pwa-migration-design.md.

// Site-wide icons/manifest worth precaching when present.
const FIXED_ASSETS = [
  "/site.webmanifest",
  "/favicon.svg",
  "/favicon.ico",
  "/apple-touch-icon.png",
  "/og/logo-192.png",
  "/og/logo-512.png",
];

// Normalize an Astro page pathname to a clean URL (trailingSlash: "never").
function pageUrl(pathname) {
  const trimmed = pathname.replace(/^\/+|\/+$/g, "");
  return trimmed === "" ? "/" : `/${trimmed}`;
}

// Recursively list URL paths of every file under <outDir>/<sub>.
function walkUrls(outDir, sub) {
  const abs = join(outDir, sub);
  if (!existsSync(abs)) return [];
  const out = [];
  for (const entry of readdirSync(abs)) {
    const rel = posix.join(sub, entry);
    if (statSync(join(outDir, rel)).isDirectory()) out.push(...walkUrls(outDir, rel));
    else out.push(`/${rel}`);
  }
  return out;
}

function serviceWorkerSource(version, precache) {
  return `// Auto-generated by scripts/pwa.mjs on build. Do not edit by hand.
const CACHE = "ymjc-${version}";
const PRECACHE = ${JSON.stringify(precache, null, 2)};

self.addEventListener("install", (event) => {
  // Resilient precache: a single failed entry must not abort the whole install
  // (unlike cache.addAll). Any gaps backfill via runtime caching on first visit.
  event.waitUntil(
    caches.open(CACHE)
      .then((cache) => Promise.allSettled(PRECACHE.map((url) => cache.add(url))))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return; // ads, GTM, analytics: untouched

  // Content-addressed build assets: cache-first (immutable).
  if (url.pathname.startsWith("/_astro/")) {
    event.respondWith(
      caches.match(req).then((hit) => hit || fetch(req).then((res) => {
        const copy = res.clone();
        caches.open(CACHE).then((c) => c.put(req, copy));
        return res;
      }))
    );
    return;
  }

  // Page navigations: network-first, fall back to cached page, then to "/".
  if (req.mode === "navigate") {
    event.respondWith(
      fetch(req)
        .then((res) => {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(req, copy));
          return res;
        })
        .catch(() => caches.match(req).then((hit) => hit || caches.match("/")))
    );
    return;
  }

  // Everything else same-origin: stale-while-revalidate.
  event.respondWith(
    caches.match(req).then((hit) => {
      const network = fetch(req).then((res) => {
        const copy = res.clone();
        caches.open(CACHE).then((c) => c.put(req, copy));
        return res;
      }).catch(() => hit);
      return hit || network;
    })
  );
});
`;
}

export default function pwa() {
  return {
    name: "ymjc-pwa",
    hooks: {
      "astro:build:done": ({ pages, dir, logger }) => {
        const outDir = fileURLToPath(dir);

        const precache = Array.from(
          new Set([
            ...pages.map((p) => pageUrl(p.pathname)),
            ...walkUrls(outDir, "_astro"),
            ...FIXED_ASSETS.filter((a) => existsSync(join(outDir, a.slice(1)))),
          ])
        ).sort();

        const version = createHash("sha256")
          .update(precache.join("\n"))
          .digest("hex")
          .slice(0, 8);

        writeFileSync(join(outDir, "sw.js"), serviceWorkerSource(version, precache));
        logger.info(`sw.js written — cache ymjc-${version}, ${precache.length} entries precached`);
      },
    },
  };
}
