export default [
    "Yo mama's so bald, we thought the sun was rising when she got up.",
    "Yo mama so bald you can see what's on her mind.",
    "Yo mama so bald that she took a shower and got brainwashed.",
    "Yo mama's so bald she curls her hair with rice.",
    "Yo mama's so bald that when she put on a sweater, folks thought she was a roll on deodorant.",
    "Yo momma so bald, you can play air hockey on her head.",
    "Yo mama's so bald, Mr. Clean got jealous.",
    "Yo mama's so bald her hair looks like stitches.",
    "Yo mama's so bald, when she goes to bed, her head slips off the pillow.",
    "Yo mama so bald that Vin Diesel thought she was his twin.",
    "Yo mama is so bald, when I rubbed her head, I could see the future.",
    "Yo mamma so bald birds land on her head.",
    "Yo mama is so bald she braids her mustache.",
    "Yo momma is so bald that when it's cloudy out at night, you still see a full moon.",
    "Yo mama is so bald, I could polish her head and take her bowling.",
    "Yo mama is so bald even the hairdressers used her head for a mirror.",
    "Yo mama so bald even a wig wouldn't help.",
    "Yo momma so bald, when I rub her head, I can see the future.",
    "Yo momma's so bald they had to replace Mr. Clean.",
    "Yo momma so bald, I can see what's on her mind.",
    "Yo mama is so bald when she takes a shower she gets brainwashed.",
    "Yo mama so bald headed she uses a toothpick as a comb."
  ]