export default [
  "Yo mamma so bald birds land on her head.",
  "Yo mama's so bald, Mr. Clean got jealous.",
  "Yo mama so bald even a wig wouldn't help.",
  "Yo mama is so bald she braids her mustache.",
  "Yo mama so bald you can see what's on her mind.",
  "Yo mama's so bald she curls her hair with rice.",
  "Yo mama's so bald her hair looks like stitches.",
  "Yo momma so bald, I can see what's on her mind.",
  "Yo momma's so bald they had to replace Mr. Clean.",
  "Yo momma so bald, you can play air hockey on her head.",
  "Yo mama so bald that Vin Diesel thought she was his twin.",
  "Yo mama so bald that she took a shower and got brainwashed.",
  "Yo momma so bald, when I rub her head, I can see the future.",
  "Yo mama is so bald when she takes a shower she gets brainwashed.",
  "Yo mama's so bald, we thought the sun was rising when she got up.",
  "Yo mama is so bald, I could polish her head and take her bowling.",
  "Yo mama is so bald, when I rubbed her head, I could see the future.",
  "Yo mama is so bald even the hairdressers used her head for a mirror.",
  "Yo mama's so bald, when she goes to bed, her head slips off the pillow.",
  "Yo momma is so bald that when it's cloudy out at night, you still see a full moon.",
  "Yo mama's so bald that when she put on a sweater, folks thought she was a roll on deodorant.",
  "Yo mama's so bald, she uses a marker to color her scalp.",
  "Yo mama's so bald, she gave the moon competition in the shine department.",
  "Yo mama's so bald, her forehead has no end in sight.",
  "Yo mama is so bald, she's thinking about getting a combover from the library.",

  "Yo mama’s so bald, she pays a team of squirrels to keep her head shaded",
  "Yo mamma is so bald, she donates to wig companies anonymously",
  "Yo mamma is so bald, even an empty nest feels overcrowded!",  "Yo momma so bald, she can't wear a turtleneck without looking like a stick of roll-on deodorant.",
  "Your mother is so bald, when she wears a black turtleneck she looks like a freshly uncapped Sharpie.",
  "Your mother is so bald, she sat down at a fortune teller's table and the psychic immediately tried to read her mind through her forehead.",
  "Yo mama so bald, her thoughts have to wear non-slip socks just to stay in her head.",
  "Yer ma's so bald, she has to use a plunger just to get her winter beanie off.",
  "Yo mama's so bald, she stepped out into the sun and accidentally generated 1.21 gigawatts of clean, renewable energy.",
  "Your mom is so bald, when she stands in front of a mirror, her reflection has to wear sunglasses.",
];
