export default [
  "Yo mamma so bald birds land on her head.",
  "Yo mama's so bald, Mr. Clean got jealous.",
  "Yo mama so bald even a wig wouldn't help.",
  "Yo mama is so bald she braids her mustache.",
  "Yo mama so bald you can see what's on her mind.",
  "Yo mama's so bald she curls her hair with rice.",
  "Yo mama's so bald her hair looks like stitches.",
  "Yo momma so bald, I can see what's on her mind.",
  "Yo momma's so bald they had to replace Mr. Clean.",
  "Yo momma so bald, you can play air hockey on her head.",
  "Yo mama so bald that Vin Diesel thought she was his twin.",
  "Yo mama so bald that she took a shower and got brainwashed.",
  "Yo momma so bald, when I rub her head, I can see the future.",
  "Yo mama is so bald when she takes a shower she gets brainwashed.",
  "Yo mama's so bald, we thought the sun was rising when she got up.",
  "Yo mama is so bald, I could polish her head and take her bowling.",
  "Yo mama is so bald, when I rubbed her head, I could see the future.",
  "Yo mama is so bald even the hairdressers used her head for a mirror.",
  "Yo mama's so bald, when she goes to bed, her head slips off the pillow.",
  "Yo momma is so bald that when it's cloudy out at night, you still see a full moon.",
  "Yo mama's so bald that when she put on a sweater, folks thought she was a roll on deodorant.",
  "Yo mama's so bald, she uses a marker to color her scalp.",
  "Yo mama's so bald, she gave the moon competition in the shine department.",
  "Yo mama's so bald, her forehead has no end in sight.",
  "Yo mama is so bald, she's thinking about getting a combover from the library.",

  "Yo mama’s so bald, she pays a team of squirrels to keep her head shaded",
  "Yo mamma is so bald, she donates to wig companies anonymously",];
