export default [
  "Yo mama is so dirty that she makes mud look clean.",
  "Yo momma so gross, her shadow leaves a grease trail.",
  "Yo momma's so dirty, even roaches won't live with her.",
  "Yo mama is so dirty that she loses weight in the shower.",
  "Yo mama is so dirty that she has to creep up on bathwater.",
  "Yo mama's teeth so yellow, I can't believe its not butter.",
  "Yo mama's breath is so bad people look forward to her farts!",
  "Yo mama's breath stinks so bad she can't help but talk shit.",
  "Yo mama's so dirty, she fertilizes her lawn by rolling in it!",
  "Yo mama's so dirty, she jumped in a river and created a mud slide!",
  "Yo mama is so dirty that when she takes a bath she becomes skinny.",
  "Yo momma's so smelly, that when she spread her legs, I got seasick.",
  "Yo mama is so dirty that even Swamp Thing told her to take a shower.",
  "Yo mama so dirty she had to wipe her feet before she walked outside.",
  "Yo mama's house is so dirty that roaches ride around on dune buggies!",
  "Yo mama's so dirty, when the wind blows people yell « Sand Storm!! »!",
  "Yo momma so dirty the only dis I'm going to give her is disinfectant.",
  "Yo momma is so stank she makes skunks smell like desert flower Air Wick.",
  "Yo mama's so greasy, on hot days she cooks bacon strips on her ass cheeks",
  "Yo Momma's teeth are so yellow, that when she smiles, traffic slows down!",
  "Yo mama house so dirty, she has to wipe her feet before she goes outside.",
  "Yo mama's so dirty, when a seed gets stuck in her ass crack it beings to grow!",
  "Yo momma's breath smelled so bad when she walked by a clock it said « Tic Tac ».",
  "Yo momma's breath so stank, when she talks to her plants they hold their breath.",
  "Yo mama is so dirty that that you can't tell where the dirt stops and she begins.",
  "Yo mama is so dirty that the US Government uses her bath water as a chemical weapon.",
  "Yo momma is so dirty she is like a chicken coop because cocks fly in and out all day.",
  "Yo mama's hair is so full of dandruff, when she shook her head, the principal called a snow day.",
  "Yo mama is so dirty that that she was banned from a sewage facility because of sanitation concerns.",
  "Yo mama is so dirty that when she tried to take a bath, the water jumped out and said « I'll wait ».",
  "Yo momma's so smelly, an old blind geezer walking by asked her « Yo, how much for the shrimp platter »?",
  "Yo momma has so much dandruff when she scratches her head people are like « Dang, is it winter already »?",
  "Yo mama's so filthy, she uses sandpaper as a washcloth.",
  "Yo mama's so dirty, she showers in mud.",
];
