export default [
  "Yo mama's so mean, she made an onion cry.",
  "Yo mama's mean, she returns borrowed sunshine.",
  "Yo mama so mean, even Hello Kitty said goodbye.",
  "Yo mama so evil, the devil sold his soul to her.",
  "Yo mama's resentful, she holds grudges against dial tones.",
  "Yo mama's bitter, she makes black coffee taste like candy.",
  "Yo mama's pathetic, pity parties have VIP sections for her.",
  "Yo mama's mean, she makes Simon Cowell look like Mr. Rogers.",
  "Yo mama's unwanted, even Nigerian princes delete her emails.",
  "Yo mama's spiteful, she dog-ears every page in library books.",
  "Yo mama’s so mean, her birth certificate is an apology letter.",
  "Yo mama's negative, she could find a flaw in a perfect circle.",
  "Yo mama's hated, people throw parties when she leaves the room.",
  "Yo mama's depressing, she makes funerals seem like a celebration.",
  "Yo mama's worthless, she couldn't sell ice to Eskimos... in July.",
  "Yo mama's unwelcome, 'Go Away' mats say 'Welcome' compared to her.",
  "Yo mama's evil, she makes Cruella De Vil look like a puppy rescuer.",
  "Yo mama's malicious, she poisons the office coffee... with instant.",
  "Yo mama's miserable, she makes Mondays look like a weekend getaway.",
  "Yo mama's irrelevant, history classes fast-forward through her life.",
  "Yo mama's gloomy, she makes thunderclouds seem like a ray of sunshine.",
  "Yo mama's unimportant, she's not even a footnote in the history of lint.",
  "Yo mama's insignificant, she makes dust motes feel like celestial bodies.",
  "Yo mama's disliked, even fruit flies hold their breath when she walks by.",
  "Yo mama's so mean, she tells her GPS to 'shut up' when it gives directions.",
  "Yo mama's wicked, she makes Freddy Krueger seem like a bedtime story teller.",
  "Yo mama's detested, the universe is actively trying to phase her out of existence.",
  "Yo mama's pessimistic, she sees the glass as half-empty, leaking, and probably poisoned.",
  "Yo mama is so mean that when she went into a haunted house, she came out with a job application.",
  "Yo mama's so evil, even Voldemort wouldn't invite her to a party.",
  "Yo mama's so evil, even Satan files a restraining order.",
  "Yo mama's so evil, her tears cure nothing.",

  "Yo mama's so evil, she makes serial killers apply for a background check!",
  "Yo mama's so evil, even Scrooge refuses to borrow money from her!",
  "Yo mama’s so evil, she writes passive-aggressive thank you notes to her therapist",];
