export default [
    "Yo momma is just like Jupiter: huge, round, and gassy.",
    "Yo mama is like the sun. Big, round, and hard to look at.",
    "Yo mama's so fat, when she fell I didn't laugh, but the sidewalk cracked up.",
    "Yo mama's so fat, when she skips a meal, the stock market drops.",
    "Yo mama's so fat, it took me two buses and a train to get to her good side.",
    "Yo mama's so fat, when she goes camping, the bears hide their food.",
    "Yo mama so fat, she wakes up in sections.",
    "Yo mama so fat, her cereal bowl has a lifeguard.",
    "Yo mama is so fat, her belly button got an echo.",
    "Yo mama is so fat, that we went to the drive-in and didn't have to pay for her because we dressed her up as a Toyota.",
    "Yo mama's so fat, if she buys a fur coat, a whole species will become extinct.",
    "Yo mama's so fat, she stepped on a scale and it said: 'To be continued.'",
    "Yo mama's so fat, she fell off both sides of the bed at the same time.",
    "Yo momma is so fat, I swerved to miss her in my car and ran out of gas.",
    "Yo mama's so fat, when she wears high heels, she strikes oil.",
    "Yo mama so fat, people keep pushing her in the water when she's at the beach so she won't die.",
    "Yo mama's so fat, she was overthrown by a small militia group, and now she's known as the Republic of Yo Mama.",
    "Yo mama so fat, that when she wanted a water bed, she just put a blanket over the ocean.",
    "Yo mama so fat, I took a picture of her last Christmas and it's still printing.",
    "Yo mama so fat, she has her own ZIP code.",
    "Yo mama's so fat, she's got more chins than a Hong Kong phone book.",
    "Yo mama's so fat, she went on a diet and caused a recession.",
    "Yo mama is so fat, she uses Google Earth to take a selfie.",
    "Yo mama is so fat, not even Dora can explore her.",
    "Yo mama is so fat, she gets group insurance.",
    "Yo mama's so fat, when she went to KFC and the cashier asked what size bucket she wanted, she said, 'The one on the roof!'",
    "Yo mam's so fat, she has to iron her shirts in the driveway.",
    "Yo mama is so fat, she has two watches one for each time zone she's in.",
    "Yo mama is so big, her belt size is 'equator.'",
    "Yo mama's so fat, that when she goes to the beach the whales start singing 'we are family.'",
    "Yo mama is so fat, when she talks to herself, it's a long-distance call.",
    "Yo mama is so fat, she left in high heels and came back in flip flops.",
    "Yo mama is so fat, that when she hauls ass, she has to make two trips.",
    "Yo mama is so fat, her job title is Spoon and Fork Operator.",
    "Yo mama is so fat, when she walked past the TV, I missed three episodes.",
    "Yo momma's so fat, when she sits around the house, she sits around the house.",
    "Yo mama's so fat, her car has stretch marks.",
    "Yo mama's so fat, she can't even jump to a conclusion.",
    "Yo mama's so fat, her blood type is Ragu.",
    "Yo mama's so fat, if she was a Star Wars character, her name would be Admiral Snackbar.",
    "Yo mama is so fat that when she was born, she gave the hospital stretch marks.",
    "Yo mama is so fat that she was cut from the cast of E.T., because she caused an eclipse when she rode the bike across the moon.",
    "Yo mama is so fat that when you get on top of her your ears pop.",
    "Yo mama is so fat that she got hit by a car and had to go to the hospital to have it removed.",
    "Yo mama is so fat that she eats \"Wheat Thicks\".",
    "Yo mama is so fat that we're in her right now!",
    "Yo mama is so fat that she went to the movie theatre and sat next to everyone.",
    "Yo mama is so fat that she has been declared a natural habitat for condors.",
    "Yo mama is so fat that when she wants to shake someones hand, she has to give directions!",
    "Yo mama is so fat that even Dora can't explore her!",
    "Yo mama is so fat that when she gets on the scale it says \"to be continued\".",
    "Yo mama is so fat that when she goes to a resturant, she looks at the menu and says \"okay!\"",
    "Yo mama is so fat that even Chuck Norris couldn't run around her.",
    "Yo mama is so fat that her neck looks like a dozen hot dogs!",
    "Yo mama is so fat that when she volunteered to clean the cages at the zoo, people would walk by and say \"Look at that hippopotamus!\".",
    "Yo mama is so fat that when she bungee jumps she goes straight to hell!",
    "Yo mama is so fat that she's got her own area code!",
    "Yo mama is so fat that she looks like she's smuggling a Volkswagon!",
    "Yo mama is so fat that she has to buy three airline tickets.",
    "Yo mama is so fat that whenever she goes to the beach the tide comes in!",
    "Yo mama is so fat that she's got Amtrak written on her leg.",
    "Yo mama is so fat that her legs are like spoiled milk - white &amp; chunky!",
    "Yo mama is so fat that I had to take a train and two buses just to get on the her good side!",
    "Yo mama is so fat that when she lies on the beach no one else gets any sun!",
    "Yo mama is so fat that that her senior pictures had to be taken from a helicopter!",
    "Yo mama is so fat that everytime she walks in high heels, she strikes oil!",
    "Yo mama is so fat that she fell and created the Grand Canyon!",
    "Yo mama is so fat that her butt drags on the ground and kids yell - \"there goes santa claus with his bag of toys!\"",
    "Yo mama is so fat that even her clothes have stretch marks!",
    "Yo mama is so fat that she has to use a VCR as a beeper!",
    "Yo mama is so fat that when she asked for a waterbed, they put a blanket over the ocean!",
    "Yo mama is so fat that she got hit by a parked car!",
    "Yo mama is so fat that they use the elastic in her underwear for bungee jumping.",
    "Yo mama is so fat that when we were playing Call of Duty, I got a 20 kill streak for killing her.",
    "Yo mama is so fat that Dracula got Type 2 Diabetes after biting her neck.",
    "Yo mama is so fat that when she fell over she rocked herself asleep trying to get up again.",
    "Yo mama is so fat that that when I tried to drive around her I ran out of gas.",
    "Yo mama is so fat that when she went to church and sat on a bible, Jesus came out and said \"LET MY PEOPLE GO!\"",
    "Yo mama is so fat that when she dances at a concert the whole band skips.",
    "Yo mama is so fat that she stands in two time zones.",
    "Yo mama is so fat that she went to the fair and the kids thought she was a bouncy castle.",
    "Yo mama is so fat that when she goes to an all you can eat buffet, they have to install speed bumps.",
    "Yo mama is so fat that the camera TAKES AWAY 10 lbs from her appearance.",
    "Yo mama is so fat that her sedan can fit 5 people... or just yo mama with the front seats removed.",
    "Yo mama is so fat that when she went to seaworld the whales started singing 'We Are Family'.",
    "Yo mama is so fat that she fell out of both sides of her bed.",
    "Yo mama is so fat that the stripes on her pajamas never end.",
    "Yo mama is so fat, Al Gore accuses her of global warning everytime she farts!",
    "Yo mama is so fat that she's got every caterer in the city on speed dial!",
    "Yo mama's so fat that when she goes on a scale, it shows her own phone number.",
    "Yo mama's so fat that she doesn't need the internet - she's worldwide.",
    "Yo mama's so fat that when she goes on a scale, it reads 'lose some weight'.",
    "Yo mama's so fat that she doesn't get dreams, she gets movies!",
    "Yo mama's so fat that when she walks, she changes the earth's rotation!",
    "Yo mama is so fat that she uses the entire country of Mexico as her tanning bed.",
    "Yo momma is so fat when she got on the scale it said, \"I need your weight not your phone number.\"",
    "Yo momma is so fat that when she went to the beach a whale swam up and sang, \"We are family, even though you're fatter than me.\"",
    "Yo momma's so fat and old when God said, \"Let there be light,\" he asked your mother to move out of the way.",
    "Yo momma is so fat when she sat on WalMart, she lowered the prices.",
    "Yo momma is so fat that Dora can't even explore her!",
    "Yo momma is so fat her bellybutton gets home 15 minutes before she does.",
    "Yo mamma is so fat she doesn't need the internet, because she's already world wide.",
    "Yo Momma's so fat when I told her to touch her toes she said, \"What are those\"?",
    "Yo momma is so fat when she went to KFC the cashier asked, \"What size bucket?\" and yo momma said, \"The one on the roof.\"",
    "Yo momma's so fat she needs cheat codes for Wii Fit.",
    "Yo momma is so fat that when she saw a yellow school bus go by full of white kids she ran after it yelling, \"TWINKIE!\"",
    "Yo mamma is so fat she walked past the TV and I missed 3 episodes.",
    "Yo momma so fat when she steps out in a yellow raincoat, the people yell, \"TAXI!\"",
    "Yo mama so fat I tried driving around her and I ran out of gas.",
    "Yo momma is so fat she sat on the rainbow and Skittles came out.",
    "Yo momma is so fat when she stepped on the scale it read, \"Get the hell off me!\"",
    "Yo mama's so fat when I pictured her in my head she broke my neck.",
    "Yo momma's so fat she can't even jump to a conclusion.",
    "Yo momma is so fat she went to church with heels on and when she came back home they were flats.",
    "Yo momma is so fat when she sat on an iPad she made a plasma TV.",
    "Yo mamma so fat when she died she broke the stairway to heaven .",
    "Yo mama is so fat on Halloween she threw on a white sheet and went as Antarctica.",
    "Yo momma so fat when she registered for MySpace there was no space left.",
    "Yo mama so fat when stepped on a scale she said, \"How does it know my credit card number?\"",
    "Yo momma is so fat that the last time she saw 90210 was on the scale.",
    "Yo momma so fat she fell out of the family tree.",
    "Yo mama is so fat when she took her dress to the dry cleaners they said, “Sorry, we don’t do curtains.\"",
    "Yo mama so fat she got arrested for carrying 10 pounds of crack.",
    "Yo mama so fat the bears have to hide their food from her when she goes camping.",
    "Your mamma's so fat people jog around her for exercise.",
    "Yo mama is so fat that when she takes a shower her feet don't get wet.",
    "Yo mama so fat the only reason she took algebra in high school was because she heard there was gonna be some pi.",
    "Yo momma is so fat you need to take two trains and a bus just to get on her good side.",
    "Yo momma so fat her favorite food is seconds.",
    "Yo momma's so fat she puts a cup of water in the bathtub and it still overflows!",
    "Yo mama so fat she fell in love and broke it.",
    "Yo mama so fat that when aliens came to invade us they said, \"Wow! Two planets in one.\"",
    "Yo momma is so fat when she sat on a quarter a booger came out of George Washington's nose.",
    "Yo momma is so fat it took Nationwide 2 years to get on her side.",
    "Yo mama so fat she got a job at the movie theater as the screen!",
    "Yo mama so fat when she goes into an elevator she has to go down.",
    "Yo momma so fat she wakes up on both sides of the bed.",
    "Yo mamma is so fat that when she showed up to watch a sumo wrestling tournament, they gave her the trophy.",
    "Yo momma so fat her belt loops have mile markers.",
    "Yo momma is so fat she tripped over Tokyo and landed in Hawaii.",
    "Your mamma so fat she uses a mattress as a maxi pad.",
    "Yo mama is so fat when she wants her photo taken she has to call Google Earth.",
    "Yo mama's so fat when she went to In and Out she couldn't get in or out.",
    "Yo Momma so fat she uses the 101 fwy for a slip 'n' slide!",
    "Yo mama is so fat that when she talks to herself, it’s a long distance call.",
    "Your mama so fat when she did a push up Earth went down.",
    "Yo mama is so fat that when she went to the movie theater she sat next to everybody.",
    "Yo momma so fat when she turned around we gave her a Welcome Back Party.",
    "Yo mama so fat that her yearbook picture was on page 20, 21, 22, and 23.",
    "Yo mama is so fat when Jabba's guard pushed her into the sarlacc pit, it choked to death.",
    "Yo mamma is so fat that when she went to the Gap, she filled it in.",
    "Yo momma's so fat she passed the window and we lost light for 4 days.",
    "Yo momma's so fat and old, when Moses wanted to part the Red Sea, he told her to do a cannon ball.",
    "Yo mama is so fat that she measures 36-24-36, and the other arm is just as big.",
    "Yo Mamma so fat she had to have a real horse on her polo shirt.",
    "Yo mamma's so fat her baby picture was taken by Neil Armstrong.",
    "Yo momma is so fat if she does jumping jacks in high heels she will strike oil!",
    "Yo momma so fat she wore a sign that said \"CAUTION: Wide Turns!\"",
    "Yo mama is so fat that black holes try to escape her.",
    "Yo mama is so fat that she can’t even jump to a conclusion.",
    "Your mama is so fat that her BMI is measured in acres. ",
    "Yo mama so fat she got titties on her back.",
    "Your momma is so fat NASA used her to fill a hole in the ozone layer.",
    "Yo momma is so fat that when she applied to be a bus driver she found out she was qualified to be the bus.",
    "Yo mama is so fat that I had to take her photo in panorama mode.",
    "Yo mama's so fat that to get her through a doorway you have to grease the doorframe and hold a Twinkie on the other side.",
    "Yo mama so fat that when she wears a yellow dress while bungee jumping people think the sun is falling.",
    "Yo mama so fat the National Hurricane Center named each of her farts.",
    "Yo mama is so fat that when she was diagnosed with a rapid flesh-eating disease, the doctor gave her twenty years to live.",
    "Yo mama is so fat that Weight Watchers won’t look at her.",
    "Your mama so fat when she fell out of the bed she fell off both sides.",
    "Yo momma so fat she added a profile picture to her Facebook and it's still loading.",
    "Yo momma is so fat Miley Cyrus uses her as a wreaking ball.",
    "Yo momma is so fat she went to the movies and sat next to everybody. ",
    "Yo momma so fat that when she farted, the second Big Bang occurred.",
    "Yo momma so fat she was on her way to McDonalds tripped over Burger King and landed on Wendy's.",
    "Yo momma so fat her belly button made it to her house 15 minutes before she did.",
    "Yo mama's so fat when she went on the scale she said, \"How does it know my credit card number?\"",
    "Yo moma so fat she wears trashbags for socks.",
    "Yo mama is so fat that her belly button doesn't have lint, it has sweaters.",
    "Yo momma so fat when she trips in California, she lands in The Philippines",
    "Yo momma so fat not even Naruto could believe it.",
    "Yo momma so fat when she stepped on a weighing scales it said ONE PERSON AT A TIME PLEASE",
    "Yo momma is so fat that when she put on a yellow dress the sun went out of business.",
    "Yo mamma is so fat when she gets her shoes shined she has to take their word for it.",
    "Yo mama so fat her belt size is hula-hoop.",
    "Yo mama is so fat that when I had sex with her I had to roll over two times to get off of her.",
    "Yo momma's so fat when she went to In-N-Out, she couldn't get in or out.",
    "Yo mamma is so fat when she went to In-N-Out Burger, she couldn't go in or out.",
    "Yo momma is so fat that when she bends over, we go into daylight savings time.",
    "Yo mama so fat whet she took her first step the grand canyon was made",
    "Yo mama so fat even Dora couldn't explore her",
    "Yo mamma is so fat she walked pass the T.V. and I missed three episodes",
    "Yo Momma's so fat that when she went up to space, there was no space!",
    "Yo mama has so many rolls of fat she has to screw on her pants.",
    "Yo mama so fat when she sat on four quarters she made a dollar bill.",
    "Yo mama is so fat and dumb she signed up for an email account because she heard it contained spam.",
    "Yo mama so fat that she stepped on a scale and two white flags popped out that said, \"I surrender!\"",
    "Yo mom is so fat when she walked in front of the window, we lost sun light for 7 days.",
    "Yo momma so fat when she auditioned for Star Wars she was cast as outer space.",
    "Your momma so fat when she turned on her PS4 the PlayStation Network crashed.",
    "Your momma so fat when she stepped on a quarter she picked up two dimes and a nickel.",
    "Yo momma so fat that when she sat on a dollar 4 quarters popped out.",
    "Yo mama so fat when she goes up to a buffet she doesn't bring a plate, she brings her chair.",
    "Yo mamma's so fat she turned an airplane into a submarine.",
    "Yo mama so fat that Bill Gates couldn't pay for her liposuction.",
    "Yo momma is so fat when you tell her to haul ass she takes three trips.",
    "Yo momma's so fat Jesus can't even lift her spirit.",
    "Your momma is so fat that your dad has to climb 15 minutes just to give her a kiss.",
    "Your mamma is so fat when she was an astronaut, scientists thought she was a planet.",
    "Your mum is so fat when she went on the scale it said, \"To be continued...\"",
    "Yo momma so fat she uses Mexico as her tanning bed.",
    "Yo Momma so fat she has her own area code.",
    "Yo mama so fat she sat at the edge of the ocean and the lifeguard said, \"Ma'am, you're blocking the tide.\"",
    "Yo mamma is so fat that when she went in the ocean, the ocean came out!",
    "Yo mama so fat that when she went swimming explorers claimed her for new land.",
    "Yo mama so fat that when she plays volleyball she plays the whole court.",
    "Yo momma's thighs are so fat you can smack them and ride the waves.",
    "Yo momma so fat that the back of her neck looked like a pack of hot dogs.",
    "Yo momma so fat when she went whale watching the people were watching her.",
    "Yo momma so fat you have to grease the door frame and hold a Mars bar on the other side just to get her through.",
    "Yo momma is so so fat that when she sat on a monster truck she made it a low-rider.",
    "Yo mama so fat the only thing keeping her from McDonald's is the door.",
    "Yo momma is so fat that when she sat on WalMart the prices got lower.",
    "Yo momma is so fat when she sat on a rainbow Skittles popped out.",
    "Yo mamma is so fat when she stepped on the scale it said her Social Security number.",
    "Yo momma is so fat the only thing stopping her from going to Jenny Craig is the door",
    "Yo momma's so fat she can't even jump to conclusions.",
    "Yo mama so fat she went for a swim  under water she opened her mouth and swallowed the whole ocean.IN ONE GULP",
    "Yo Momma so fat she got arrested at the airport for carrying 10 pounds of crack",
    "Yo momma so fat when she got her period people thought there was a volcano.",
    "Yo momma so fat Earth is tilted because she fell out of her chair.",
    "Yo mama so fat that I would insult her, but cows are sacred where I come from.",
    "Yo momma's so fat she needs a helicopter to take a selfie.",
    "Yo momma is so fat she has her own gravitational pull.",
    "Yo mama is so fat that when she got her shoes shined, she had to take the guy’s word for it.",
    "Yo mamma so fat when she went to get her picture taken the photographer told her to say \"Cheese\" and she said, \"Where?\"",
    "Yo mama so fat I took 2 train rides and one bus to get to her good side.",
    "Your mom is so fat she went to a party in a metallic dress and people thought she was a keg.",
    "Yo momma so fat she plays billiards with the planets.",
    "Yo momma is so fat she wakes up in sections.",
    "Yo momma is so fat she makes free willy look like a tic-tac!",
    "Yo momma's so fat that her Patronus is a cake.",
    "your mama so fat people jog round her for excercise",
    "Yo mamma is so fat when she has to make a long distance call just to talk to herself.",
    "Yo momma so fat when she jumped for joy she got stuck.",
    "Yo momma is so fat her blood type is ragù.",
    "Yo mamas so fat she used two buses for roller skates.",
    "Yo mama's so fat Honey Boo Boo's mom tried to give her a massage and got lost!",
    "Yo mama so fat she tried to climb Mountain Dew.",
    "Yo mamma is so fat she wore a yellow shirt and the Sun said I am out of the job",
    "Yo momma is so fat, I took a picture of her last Christmas and it's still printing.",
    "Yo momma's so fat, that when she fell, no one was laughing but the ground was cracking up.",
    "Yo momma is so fat, when she sat on an iPod, she made the iPad!",
    "Yo momma's so fat, that when she went to the zoo, the hippos got jealous.",
    "Yo momma's so fat, she got baptized at Sea World.",
    "Yo momma's so fat, she has more rolls than a bakery.",
    "Yo momma's so fat, her baby pictures were taken by satellite.",
    "Yo momma is so fat, when she sat on the back of the bus it did a wheelie.",
    "Yo momma's so fat, she wore a black bathing suit to the pool and everyone yelled \"oil spill!\"",
    "Yo momma's so fat, the only way to get her out of a telephone booth is to grease her thighs and throw a Twinkie in the street.",
    "Yo momma's so fat, she tripped over Wal-Mart, stumbled over K-Mart, and landed on Target.",
    "Yo mama is so fat, when she stepped on a scale it said, \"One person at a time please.\"",
    "Yo momma's so fat, when she farted, she launched herself into orbit.",
    "Yo momma's so fat, her belt size is \"Equator.\"",
    "Yo mamma is so fat, the only good grade she got in school was an \"A\" in lunch.",
    "Yo momma's so fat, when she gets in an elevator, it has to go down.",
    "Yo momma's so fat, her measurements are 36-24-26, and that's just her left arm.",
    "Yo mama's so fat, when she steps on a scale, it says, \"Please step out of the car.\" ",
    "Yo momma's so fat, when she uses the keyboard she presses every key at once!",
    "Yo momma so fat, she doesn't need internet, she's already worldwide.",
    "Yo momma's so fat, when she was floating in the ocean, Spain claimed her for the new world.",
    "Yo momma's so fat, the Hogwarts Sorting Hat put her in all 4 houses!",
    "Yo momma's so fat, she only knows 3 letters of the alphabet: KFC.",
    "Yo mama's armpit is so hairy it looks like she has Bigfoot in a headlock.",
    "Yo momma's so fat, when I swerved to avoid her in the street I ran outta gas.",
    "Yo momma's so fat, even Dora can't explore her.",
    "Yo Mama is so fat, when she pressed the UP button on the elevator it went DOWN.",
    "Yo mama so fat, Dracula sucked her blood and got diabetes.",
    "Yo mamma is so fat, black holes get sucked into her.",
    "Yo mamma's so fat, I don't have to make a joke.",
    "Yo mama so fat, she has her own zip code.",
    "Yo momma's so fat, when she went to the beach, the whales sang, \"We are family!\" ",
    "Yo momma's so fat, she wakes up in sections.",
    "Yo momma's so fat, she played the role of the boulder in the first Indiana Jones movie.",
    "Yo mama so fat, when she sweats she causes a tsunami.",
    "Yp mama so fat, she caused millions of dollar property damage.",
    "Yo mamma is so fat, Bill Gates became broke after buying her dinner.",
    "Yo momma's so fat, that when she rubs her thighs together, I smell bacon.",
    "Yo momma's so fat, she fell into the Grand Canyon and got stuck!",
    "Yo momma's so fat, when we asked her what her hometown is, she said, \"Buffet.\" ",
    "Yo mama so big she got hit by a bus and said, \"Hey, who threw a rock at me?\"",
    "Yo momma's so fat, when she ordered a water bed, they put a blanket over the Atlantic Ocean.",
    "Yo mamma's so fat, she IS the circle of life.",
    "Your mum is like the sun: big, round, and hard to look at.",
    "Yo momma so hairy Bigfoot took a picture of HER!",
    "Yo momma's so fat, when she jumped for joy she got stuck!",
    "Yo momma's so fat, she's on both sides of the family.",
    "Yo mama so fat, she's got more rolls than a bakery.",
    "Yo momma's so fat, she wore a red sweater and everyone thought she was the Kool-Aid man.",
    "Yo momma's so fat, when she tripped in Ohio, Tokyo had an aftershock.",
    "Yo momma's so fat, when she went to Sizzler she got a group discount.",
    "Yo momma's so fat, when she bungee jumps, she brings down the bridge, too.",
    "Yo mamma so fat, when she plays paintball her teammates hide behind her.",
    "Yo momma is so fat, she puts lipstick on with a paint roller.",
    "Yo mama is so fat, she's the reason the Earth tilts on its axis.",
    "Yo mama's so fat, her soup bowl came with a lifeguard.",
    "Yo momma's so fat, she has her own zip code 900daaaaaaaaaaaaaaaaaaaaaaamn.",
    "Yo mama so ugly, your father brings her to work so he doesn't have to kiss her goodbye.",
    "Yo mama so fat, she puts her belt on with a boomerang.",
    "Yo mama so fat, half of her is in a parallel universe.",
    "Yo momma is so fat, Stephen Hawkings black hole theory was based on her asshole.",
    "Yo momma so fat, her shadow puts dents in the ground.",
    "Yo mama so hairy Bigfoot is offended.",
    "Yo momma's so fat, she wears a watch on each arm. One for each time zone.",
    "Yo momma's so fat, when I said I wanted \"pigs in a blanket,\" she got back in bed.",
    "Yo mama's so fat, she has to grease her hands to put them in her pockets. ",
    "Yo momma so fat, she broke the FAMILY tree!",
    "Yo mamma so fat, when she jumped up, she got stuck in the air!",
    "Yo momma so fat, her bellybutton's got an echo.",
    "Yo momma's so fat, the whale from Free Willy freed her!",
    "Yo mama so fat, her shadow broke the pavement.",
    "Yo momma's so fat, when she died in Call of Duty, the other player got a 10 kill streak!",
    "Yo momma so fat, Miley Cyrus uses her as a wrecking ball!",
    "Yo momma's so fat, when she walks backwards you hear, \"Beep! Beep! Beep!\"",
    "Yo momma's so fat, she could sell shade.",
    "Yo momma'so fat, if she was a witch, her broomstick would be a broomtree!",
    "Yo momma's so fat, her stomach got a cell phone to call her mouth when it's time to eat.",
    "Yo momma so fat, she uses the Kool-Aid man for a teacup.",
    "Yo momma's so fat, your dad had to roll over twice before he could get off her.",
    "Yo momma's so fat, that I couldn't have sex with her until I rolled her in flour and found the wet spot.",
    "Yo momma is so fat, the only thing stopping her from getting a big mac was the door.",
    "Yo momma so fat, even Dora couldn't explore her!",
    "Yo momma so fat, that when she went skydiving, people thought it was a meteor",
    "Yo Momma is so fat, when she switches her cell phone from one ear to the other she get billed for roaming.",
    "Yo mama so fat, it took me two buses and a train just to get on her good side.",
    "Yo mama's so fat, when she talks to herself it's a long-distance call.",
    "Your mom is so fat, she made an email account just so she could eat the spam.",
    "Yo mamma so fat, she wears two watches to keep track of the time zones she's in.",
    "Yo mamma so fat, when she was swimming she was mistaken for an island!",
    "Yo mamma is so fat, people exercise by jogging around her.",
    "Yo momma's so fat, she sat on a rainbow, and Skittles popped out!",
    "Yo momma's so fat, it took me two planes, a train, and a bike ride just to get on her good side.",
    "Yo momma's so big, that when she stops walking, she has to put her hazard lights on.",
    "Yo momma's so fat, that when she goes out to a restaurant, she looks at the menu and says, \"sounds good.\"  ",
    "Yo momma's so fat, she put on a Malcolm X T-shirt, and a helicopter tried to land on her.",
    "Yo momma's so fat, she went bungee jumping and went straight to Hell.",
    "Yo momma's so fat, she has to iron her clothes in the driveway.",
    "Yo momma's so fat, when she went skydiving over Iraq, everyone thought America dropped a nuke.",
    "Yo momma's so fat, when she walked in front of the television, I missed three commercials.",
    "Yo momma's so fat, the only thing that's attracted to her is gravity.",
    "Yo momma's so fat, when she put on high-heels and walked out onto the street, she struck oil!",
    "Yo momma's so fat, her butt has its own congressman.",
    "Yo momma's so fat, I tried to walk around her and got lost.",
    "Yo momma's so fat, every time she turns around it's her next birthday.",
    "Yo momma's so fat, she went to Jenny Craig and they said, \"Sorry, we don't do miracles.\"",
    "Yo momma's so fat, she has to do a Slip 'N Slide on the 405 freeway.",
    "Yo momma's so fat, she wears a VCR as a beeper.",
    "Yo momma's so fat, when we played hide and seek, I spotted her behind the Himalayas.",
    "Yo momma's so fat, she needs one bar stool for each butt cheek.",
    "Yo momma's so fat, she sat on a Nintendo GameCube and it turned into a Game Boy.",
    "Yo momma's so fat, when she went to the zoo, elephants began throwing peanuts at her.",
    "Yo momma's so fat, they sent her into space and she clogged up a black hole!",
    "Yo momma so dumb, she tried to eat a power mac because she thought it was better than a big mac.",
    "Your momma's so fat, when she takes a selfie she's gotta put her camera on panoramic mode!",
    "Yo momma is so fat, when she sat on an oak tree she made a bonsai.",
    "Your momma is so fat, when she farts even Krakatoa is jealous.",
    "Yo momma's so fat, when she sits down, she's three feet taller.",
    "Yo momma's so fat, when she runs, she makes the CD player skip at the radio station.",
    "Yo momma's so fat, she wears an asteroid belt.",
    "Yo momma's so fat, when I got on top of her, my ears popped.",
    "Yo momma's so fat, her yearbook picture is an aerial photograph.",
    "Yo momma so fat, she broke a world record by falling on it",
    "Yo mama so scrawny she makes skinny jeans look fat."
  ]
  