export default [
  "Yo mama is so hairy, people think she's an Ewok.",
  "Yo mama is so hairy she shaves with a weed-whacker.",
  "Yo mama so hairy when I hugged her I got a rug burn.",
  "Yo momma so hairy when she shaved she lost 200 pounds",
  "Yo momma's so hairy, she could be sold as a Chia Pet.",
  "Yo mama’s so nice she’d give me the hair off her back.",
  "Yo mama so hairy, she shaves her legs with a lawnmower.",
  "Yo mama is so hairy that Jane Goodall follows her around.",
  "Yo mama is so hairy that Bigfoot wants to take HER picture!",
  "Yo mama is so hairy that she got a trim and lost 20 pounds.",
  "Yo mama's chest is so hairy, her breasts look like coconuts.",
  "Yo mamma is so hairy when you were born you had carpet burn.",
  "Yo mama's so hairy, you were born with third-degree rug burn.",
  "Yo mama has so much hair on her upper lip that she braids it.",
  "Yo mama is so hairy that you almost died of rugburn at birth!",
  "Yo momma is so hairy, the only language she speaks is Wookie.",
  "Yo mama is so hairy that she looks like Bigfoot in a tank top.",
  "Yo mamma is so hairy that she cut her hair and lost 20 pounds.",
  "Yo mama is so hairy that she shaves her legs with a weedwacker.",
  "Yo mama so hairy Jane Goodall set up a base camp in her bathroom.",
  "Yo mama is so hairy that she gets mistaken for Chewbacca's cousin.",
  "Yo mama’s hair is so long, Rapunzel takes styling lessons from her.",
  "Yo mama is so hairy that the only language she can speak is wookie.",
  "Yo mama's so hairy, she has to comb her wrist to see what time it is.",
  "Yo mama is so hairy that she looks like a Chia pet with a sweater on.",
  "Yo mama is so hairy that she looks like she has Buckwheat in a headlock.",
  "Yo mama is so hairy that if she could fly she'd look like a magic carpet.",
  "Yo momma so hairy, she has to use a lawnmower to shave her underarm hair.",
  "Yo mama is so hairy that they filmed « Gorillas in the Mist » in her shower!",
  "Yo mama is so hairy that her armpits look like she has Don King in a headlock.",
  "Yo mama's armpits are so hairy, it looks like she's got Buckwheat in a headlock.",
  "Yo mamma so hairy when she lifted her armpit she said « Welcome to the jungle ».",
  "Yo mama is so hairy that when I took her to a pet store they locked her in a cage.",
  "Yo mama so hairy that when she went to the pet store they locked her up in a cage!",
  "Your momma is so hairy when she opens her legs it says « Welcome to Busch Gardens ».",
  "Yo momma's so hairy when she went too the zoo everybody screamed « The gorilla's loose »!",
  "Yo mama is so hairy that people run up to her and say « Chewbacca, can I get your autograph »?",
  "Yo mama is so hairy that two birds made nests in her armpits and she doesn't even know about it!",
  "Yo mama is so hairy that if you shaved her legs, you could supply wigs for the entire Hair Club for Men.",
  "Yo momma is so hairy, when she went to the movie theater to see Star Wars, everybody screamed and said « IT'S CHEWBACCA »!",
  "Yo mama’s so hairy that when she went to see the new Star Wars movie, everyone thought Chewbacca was making a promotional appearance.",
  "Yo mama so hairy Bigfoot is offended.",
  "Yo mama's armpit is so hairy it looks like she has Bigfoot in a headlock.",
  "Yo momma so hairy Bigfoot took a picture of HER!",
  "Yo mama's so hairy, she needs a lawnmower for a razor.",
  "Yo mama's so hairy, she got mistaken for a bear on a camping trip.",
  "Yo mama's so hairy, her shampoo comes in gallon drums.",
  "Yo mama is so hairy, she could start her own wildlife preserve!",

  "Yo mama's hair is so thick, it's a full-time job for three lumberjacks to maintain!",
  "Yo mamma's so hairy, she's got a unibrow that connects to her knee!",
  "Yo mama's hair is so dense, she uses a metal detector to find her earrings",
  "Yo mamma's so hairy, she could make a wig for the whole Slytherin House!",
  "Yo mama's hair is so thick, they need a crane to lift it when she gets a perm!",
  "Your mom is so furry, she tried to pay for groceries with a handful of cedar chips.",  "Ya mama so hairy, her passport photo is just a high-definition close-up of a kiwi fruit.",
];
