export default [
  "Yo mama is so greasy that she sweats Crisco!",
  "Yo mama is so nasty that her tits leak sour milk.",
  "Yo mama so nasty, she makes speed stick slow down.",
  "Yo mama is so greasy that Texaco buys Oil from her.",
  "Yo mama is so greasy that her freckles slipped off.",
  "Yo mama is so nasty that her shit is glad to escape.",
  "Yo mama is so nasty that she brings crabs to the beach.",
  "Yo mama is so greasy that she uses bacon as a band-aid!",
  "Yo mama is so nasty that she calls Janet « Miss Jackson ».",
  "Yo mama is so nasty that next to her a skunk smells sweet.",
  "Yo mama is so nasty that even dogs won't sniff her crotch.",
  "Yo mama is so nasty that the fishery pays her to stay away.",
  "Yo mama is so nasty that she bit the dog and gave it rabies.",
  "Yo mama is so nasty that she has more crabs then Red Lobster.",
  "Yo momma is so nasty when she farts the smoke alarm goes off.",
  "Yo momma so nasty they slapped a bio hazard sign on her back.",
  "Yo mama is so nasty that a skunk smelled her ass and passed out.",
  "Yo mama is so nasty that she's got more clap than an auditorium.",
  "Yo mama so nasty her farts are classified as biological weapons.",
  "Yo mama is so nasty that she has to use Right Guard and Left Guard.",
  "Yo mama is so greasy that she's labeled as an ingredient in Crisco.",
  "Yo mama is so greasy that I buttered my popcorn with her leg hairs.",
  "Yo mama so nasty I told her to do the robot and now R2-D2 has crabs!",
  "Yo mama's teeth are so yellow that traffic slows down when she smiles!",
  "Your mom's so nasty she puts ice down her pants to keep her crabs fresh.",
  "Yo mama is so nasty that her crabs use her tampon string as a bungee cord.",
  "Yo mama is so nasty that I chatted with her on MSN and she gave me a virus.",
  "Yo mama is so nasty that every time she opens her mouth she's talking shit.",
  "Yo mama is so nasty that the only dis I want to give her is a disinfectant.",
  "Yo mama is so greasy that she squeezes Crisco from her hair to bake cookies.",
  "Yo mama is so nasty that she only changes her drawers once every 10000 miles.",
  "Yo mama is so greasy that if Crisco had a football team, she'd be the mascot.",
  "Yo mama is so greasy that you could fry a chicken dinner for 12 on her forehead.",
  "Yo momma so nasty when she went to take a shower the soap-on-a-rope hung itself.",
  "Yo mama is so nasty that that pours salt water down her pants to keep her crabs fresh.",
  "Yo mama is so nasty that I when I talked to her on the phone, she gave me an ear infection.",
  "Yo mama's teeth are so rotten that when she smiles it looks like she has dice in her mouth.",
  "Yo mama is so nasty that when you were being delivered, the doctor was wearing the oxygen mask.",
  "Yo mama is so greasy that she sweats butter and syrup and has a full time job at Denny's wiping pancakes across her forehead.",
  "Yo mama is so nasty that she has a sign by her crotch that says: « Warning: May cause irritation, drowsiness, and a rash or breakouts ».",
  "Yo momma is so nasty she made Right Guard turn left!",
  "Yo mama's so nasty, even her shoes are afraid of her feet.",
  "Yo mama's so nasty, she makes public restrooms look pristine.",
  "Yo mama's so nasty, her burps cause plant death.",
];
