export default [
  "Yo mama so old, she had to babysit Jesus.",
  "Yo mama's so old she used to babysit Jesus.",
  "Yo momma's so old, she farts out mummy dust.",
  "Yo mamma is so old she has autographed Bible.",
  "Yo mama so old she farts dust and shits rust.",
  "Yo Momma so old, God was her first boyfriend.",
  "Yo mama so old, she has Jesus' beeper number.",
  "Yo mama is so old that she baby-sat for Jesus.",
  "Yo mama is so old that she owes Jesus a dollar.",
  "Yo mama is so old, she has an autographed Bible.",
  "Yo momma's so old, she still owes Moses a dollar.",
  "Yo momma's so old, her first car was a Model T-Rex.",
  "Yo mama is so old, creationists deny her existence.",
  "Yo mama's so old, she remembers when dirt was clean.",
  "Yo mama is so old that she ran track with dinosaurs.",
  "Yo momma's so old, she left her purse on Noah's Ark.",
  "Yo mama jokes are old and overused just like yo mama!",
  "Yo mamma so old she has a Bible autographed by Jesus.",
  "Yo mama's so old, she forgot her purse on Noah's ark.",
  "Yo momma is so old she sat next to Moses in preschool.",
  "Yo momma is so frickin old her breast milk is powdered.",
  "Yo momma's so old, Jurassic Park brought back memories.",
  "Yo mama is so old that she DJ'd at the Boston Tea Party.",
  "Yo mama is so old that her memory is in black and white.",
  "Yo mama is so old that she co-wrote the Ten Commandments.",
  "Yo mama so old, her high school photo was a cave painting",
  "Yo mama is so old that she drove a chariot to high school.",
  "Yo mama is so old that she learned to write on cave walls.",
  "Yo mamma so old when I tapped her back her boobs fell off.",
  "Yo mamma's so old, when I told her to act her age she died",
  "Yo mama so old, her birth certificate is in Roman numerals.",
  "Yo mama is so old that she has Adam &amp; Eve's autographs.",
  "Yo momma is so old, her birth certificate says « EXPIRED ».",
  "Yo mama is so old, the back of her head looks like a raisin.",
  "Yo mama is so old that she sat next to Jesus in third grade.",
  "Yo mama so old, she knew 50 Cent when he was only a quarter.",
  "Yo momma's so old, she sat in front of Jesus in first grade.",
  "Yo momma's so stupid, she cooks Indian curry with Old Spice.",
  "Yo mama is so old that she owes Fred Flintstone a food stamp.",
  "Yo mamma is so old she knew Burger King when he was a prince.",
  "Yo mamas so old, she knew Gandalf when he only had a mustache.",
  "Your momma is so old she has an autographed copy of the Bible.",
  "Yo mama is so old that she took her drivers test on a dinosaur.",
  "Your momma is so old when her breast milk comes out it's powder.",
  "Yo momma's so old, when I asked for her ID, she handed me a rock",
  "Yo mama so old, she walked out of a museum and the alarm went off.",
  "Yo mama is so old that she planted the first tree at Central Park.",
  "Yo mama is so old that she has a picture of Moses in her yearbook.",
  "Yo momma's so old, she got the first copy of the Ten Commandments.",
  "Yo momma's so old, she has Roman Numerals on her birth certificate.",
  "Yo mama is so old that the candles cost more than the birthday cake.",
  "Yo momma's so old, her first job was as Cain and Abel's baby-sitter.",
  "Yo momma is so old, I slapped her in the back and her boobs fell off.",
  "Yo momma is so old she knew the Burger King when he was still a prince.",
  "Yo momma is so old that on her birth certificate it said expired on it.",
  "Yo mama is so old she remembers when the Mayans published their calendar.",
  "Yo mama is so old that she walked into an antique store and they kept her.",
  "Yo mama is so old that she knew Cap'n Crunch while he was still a private.",
  "Yo mama is so old that she needed a walker when Jesus was still in diapers.",
  "Yo mama is so old that the key on Ben Franklin's kite was to her apartment.",
  "Yo momma so old, when we watched Jurrasic Park she started having flashbacks.",
  "Yo mama's so old, when she was born, the Dead Sea was still just getting sick.",
  "Yo mama is so old when God said «,Let there be light », she flipped the switch.",
  "Yo mama is so old that she's mentioned in the shout out at the end of the bible.",
  "Yo mama is so old, she walked into an antique store, and they didn't let her leave.",
  "Yo mama is so old that she called the cops when David and Goliath started to fight.",
  "Yo momma's so old, when Moses parted the Red Sea, she was on the other side fishing.",
  "Yo mama is so old that she knew the Beetles when they were the New Kids on the Block.",
  "Yo momma's so old, the fire department is on standby when you light her birthday cake.",
  "Yo mama is so old that when Moses split the red sea, she was on the other side fishing.",
  "Yo momma's so old, that when God said «,Let there be light », she had to flip the switch!",
  "Yo mama is so old that when God said « Let there be light » she was there to flick the switch.",
  "Yo momma's so fat and old, when Moses wanted to part the Red Sea, he told her to do a cannon ball.",
  "Yo momma's so smelly, an old blind geezer walking by asked her «,Yo, how much for the shrimp platter »?",
  "Yo momma's so fat and old when God said «,Let there be light », he asked your mother to move out of the way.",
  "Yo momma's so old, they had to take her tampon to the natural history museum to find out what period it came from.",
  "Yo mama so old her Social Security number is 1.",
  "Yo mama so old, she was a waitress at The Last Supper.",
  "Yo mama is so old that when she farts, dust comes out!",
  "Yo mama so old she knew Mr. Clean when he had an Afro.",
  "Yo mamma so old, that on her birth certificate says 'EXPIRED' on it.",
  "Yo momma so old, her first Christmas, WAS the first Christmas!",
  "Yo momma's so old, she knew Burger King while he was still a prince.",
  "Yo mama is so old that I told her to act her own age, and she died.",
  "Yo mama is so old that when she was young rainbows were black and white.",
  "Yo mama is so old that that when she was in school there was no history class!",
  "Yo mama’s so old, when she breast feeds, people mistake her for a fog machine!",
];
