export default [
  "Your mamma so poor she washes paper plates.",
  "Yo mama is so poor that she washes paper plates.",
  "Yo mama's so poor, Nigerian princes wire her money.",
  "Yo mama is so poor Nigerian scammers wire HER money!",
  "Yo mama is so poor that she has to take the trash IN.",
  "Yo mama's so cheap, she reuses dental floss... for sewing.",
  "Yo mama is so poor that she can't afford to pay attention!",
  "Yo mama is so poor that burglars break in and leave money.",
  "Yo momma's so poor, she hangs the toilet paper out to dry.",
  "Yo mama is so poor that your TV got 2 channels: ON and OFF.",
  "Yo mama is so poor that she watches TV on an Etch-A-Sketch.",
  "Yo mama is so poor she couldn't afford to apply for Medicare!",
  "Yo mama is so poor that the bank repossesed her cardboard box.",
  "Yo mama is so poor that she married young just to get the rice!",
  "Yo mama is so poor that for halloween, her trick was the treat.",
  "Yo mama so poor, that she goes to KFC to lick people's fingers.",
  "Yo momma's so poor, she watches television on an Etch A Sketch.",
  "Yo mama is so poor that her face is on the front of a foodstamp.",
  "Yo mama so poor, your family ate cereal with a fork to save milk.",
  "Yo momma's so poor, burglars break into her home and leave money.",
  "Yo mama is so poor that when I ring the doorbell she says « DING »!",
  "Yo mama is so poor that I saw her wrestling a squirrel for a peanut.",
  "Yo mama is so poor that when yo family watches TV, they go to Sears.",
  "Yo mama so poor her front door and back door are on the same hinges.",
  "Yo mama is so poor she waves a popsicle around for air conditioning.",
  "Yo mama is so poor, she chases the garbage truck with a grocery list.",
  "Yo momma's so poor, when I rang her doorbell, she said « Ding-dong ».",
  "Yo mamma so poor, she ran after the garbage truck with a shopping list",
  "Yo mama is so poor that I came over for dinner and she read me recipes.",
  "Yo mama is so poor that her front and back doors are on the same hinge.",
  "Yo mama is so poor that she can't even afford to go to the free clinic.",
  "Yo momma so poor the only letters she knows in the alphabet are « EBT ».",
  "Yo mama is so poor that she has to wear her McDonald's uniform to church.",
  "Yo mama is so poor that when I ring the doorbell I hear the toilet flush!",
  "Yo momma so poor she went to Mcdonald's and tried to put a shake on layaway.",
  "Yo mama is so poor, she created a Gmail account just so she can eat the spam.",
  "Yo momma's so poor, ya'll ate cereal with a fork so that you could save milk!",
  "Yo mama is so poor that she went to McDonald's and put a milkshake on layaway.",
  "Yo mama is so poor that she had to get a second mortgage on her cardboard box.",
  "Yo mama is so poor that she can't even put her two cents in this conversation.",
  "Yo mamma is so poor when people ring the door bell they hear the toilet flush.",
  "Yo mama so poor when you walk in her house's front door you're in the backyard.",
  "Yo mama is so poor when she goes to KFC, she has to lick other people's fingers.",
  "Yo mama is so poor that she's got more furniture on her porch than in her house.",
  "Yo mama is so poor that she got in an elevator and thought it was a mobile home.",
  "Yo mama's so poor, that her doormat doesn't say « welcome », it says « welfare ».",
  "Yo momma is so poor she went running after the garbage truck with a grocery list.",
  "Your mom's so poor she waits outside KFC to lick people's fingers after they eat.",
  "Yo momma's so poor, I went through her front door and tripped over the back fence.",
  "Yo mama is so poor that she lives in a two story Dorrito bag with a dog named Chip.",
  "Yo momma's so poor that she has to lick people's fingers when they come out of KFC!",
  "Yo mama is so poor that I went through her front door and ended up in the back yard.",
  "Yo mama is so poor that I saw her running after a garbage truck with a shopping list.",
  "Yo mama is so poor that she waves around a popsicle stick and calls it air conditioning.",
  "Yo mama is so poor that her idea of a timeshare is a few days camped out under a bridge.",
  "Yo mama is so poor that I stepped on her skateboard and she said « Hey, get off the car »!",
  "Yo mama is so poor that after I pissed in your yard, she thanked me for watering the lawn.",
  "Yo mama is so poor that her idea of a fortune cookie is a tortilla with a food stamp in it.",
  "Yo mama so poor that when somebody stepped on her cigarette she said « Who turned off my heat »?",
  "Yo momma's so poor, when I told her about the Last Supper, she thought the food stamps had run out.",
  "Yo momma's so poor, I once threw a stone at a garbage can, and out she popped saying « Who knocked »?",
  "Yo momma's so poor, I asked her where the facilities were and she replied « Pick a corner, any corner ».",
  "Yo mama is so poor that the closest thing to a car she has is a low-rider shopping cart with a box on it.",
  "Yo momma's so poor, when I asked her what was for dinner she put her feet on the table and said « Corn ».",
  "Yo mama is so poor that when I asked what was for dinner, she pulled her shoelaces off and said « Spagetti ».",
  "Yo mama is so poor that when I saw her in the park digging up plants, she said she was « getting groceries ».",
  "Yo mama so poor when I went into her house and stepped on a cigarette, she said « Who turned off the heater »?",
  "Yo momma's so poor, when I visited her trailer, two cockroaches tripped me and a rat tried to steal my wallet.",
  "Yo mama so poor when I went to her house and stepped on a lit cigarette she said « Who turned the lights out »?",
  "Yo momma is so poor I saw her kicking a trash can so I asked « What are you doing »? and she said « I'm moving ».",
  "Yo Momma's so poor I stepped in a puddle, and her head popped out and said « WHAT ARE YOU DOINF IN MY BATHTUB! »?",
  "Yo momma's so poor, I visited her house, tore down the cob webs, and she screamed « Who's tearing down the drapes »!",
  "Yo mama is so poor that I walked into her house and swatted a firefly and Yo Mama said « Who turned off the lights »?",
  "Yo mama is so poor that I walked into her house, asked to use the bathroom, and she said « 3rd bucket to your right ».",
  "Yo momma is so poor that when I asked her whats for dinner tonight she lit her pocket on fire and said « hot pocket ».",
  "Yo mama is so poor that when I walked inside her house and put out a cigarette, she said « who turned off the heater »?",
  "Yo mama is so poor that I went to her house and tore down some cob webs, and she said « Who's tearing down the drapes »?",
  "Yo momma is so poor for Christmas she took a box, put two sticks on it, spun it around, and said « Here's your Xbox 360 ».",
  "Yo mama is so poor that when I saw her kicking a can down the street, I asked her what she was doing, and she said, 'Moving.'",
  "Yo mama is so poor that when I went over to her house for dinner and grabbed a paper plate, she said « Don't use the good china »!",
  "Yo mama is so poor that she was in K-Mart with a box of Hefty bags and when I asked her what she was doing she said « Buying luggage ».",
  "Yo momma's so poor, when she asked me over to dinner, I took a paper plate from the kitchen and she screamed « Don't use the good china »!",
  "Yo mama is so poor that when I saw her rolling some trash cans around in an alley, I asked her what she was doing, she said « Remodeling ».",
  "Yo momma's so poor, I walked into her home, asked if I could use her toilet, and she said « Sure thing, it's the fourth tree on your right ».",
  "Yo mama is so poor that when she tells people her address, she says « it's in the second alley from main street, beside the yellow dumpster ».",
  "Yo mama is so poor that when I saw her walking down the street with one shoe and said « Hey miss, lost a shoe »? she said « Nope, just found one »!",
  "Yo mamma so poor, when I saw her walking down the street with one shoe on, I stopped and said « You lost a shoe »! and she said « No, I found a shoe »!",
  "Yo mama is so poor that we were on a road trip and she stopped by a dumpster and got out. I said « what are you doing » and she said I'm « booking a hotel »!",
  "Yo mama's so poor, the ducks throw bread at her.",
  "Yo mama's so poor, she can't even afford to pay attention.",
  "Yo mama's so poor, pigeons drop crumbs for her.",
];
