export default [
  "Yo mama so short she can 69 with Yoda.",
  "Yo mama is so small she can't even get high.",
  "Yo mama is so short that she models for trophys.",
  "Yo mama's so small, she hang glides with a Dorito.",
  "Yo mama so short, she has to slam dunk her bus fare.",
  "Your mum's so small she can do pull-ups on a staple.",
  "Yo momma is so short, she hang glides with a Dorito!",
  "Yo mama so short, people thought she was a Funko Pop.",
  "Yo mama is so short that she can limbo under the door.",
  "Yo mama is so short that she does pull-ups on a staple.",
  "Yo mama is so small she committed suicide off the curb.",
  "Yo mama's so short that she trips on her tampon string.",
  "Yo momma so short, she needs a ladder to pick up a dime.",
  "Yo mama is so short that her homies are the Keebler Elfs.",
  "Yo mama is so short that she has to look up to look down.",
  "Yo momma so short she can tie her shoes while standing up.",
  "Yo mama is so short that she can play handball on the curb.",
  "Yo mama is so short that she can do push-ups under the door.",
  "Yo mama is so short that she uses a condom for a sleeping bag.",
  "Yo mama is so short that she has to use a ladder to pick up a dime.",
  "Yo mama's house so small, you have to go outside to change your mind.",
  "Yo mamma so short when she tried to smoke weed she couldn't get high.",
  "Yo momma is so short she does back flips in the space under the door.",
  "Yo mama is so short that when she sneezes, she hits her head on the floor.",
  "Yo mama is so short that she makes Gary Coleman look like Shaquille O'Neal.",
  "Yo mamma so short, when she sits on a dime, her feet don't touch the ground!",
  "Yo mama so short, she went to see Santa, and he told her to get back to work.",
  "Yo momma is so short, when she went to meet Santa he said «,Go back to work »!",
  "Yo mama is so short that she has to get a running start to get up on the toilet.",
  "Yo mama's so short that when she sat on the curb her feet didn't touch the ground.",
  "Yo mama's house is so small, when she drops a Kleenex she has wall-to-wall carpeting.",
  "Yo mama is so short that when I was dissin' her she tried to jump kick me in the ankle.",
  "Yo mama is so short, you can make a life size sculpture of her using one can of Play-Doh.",
  "Yo mama house so small that when she orders a large pizza, she has to go outside to eat it.",
  "Yo momma is so short, you can see her feet on her driver's license.",
  "Yo mama's so short, she can hang glide on a Dorito.",
  "Yo mama's so short, her shoes double as booster seats.",
];
