export default [
  "Yo momma's so ugly, she gotta be yo momma.",
  "Yo mama so ugly even aliens won't probe her.",
  "Yo mama's so ugly, she scares away stray cats.",
  "Yo momma is so ugly she made my happy meal cry",
  "Yo mama's so ugly, she could make an onion cry.",
  "Yo mama so ugly she's the reason Sonic runs fast.",
  "Yo mamma so ugly it looks like her neck threw up.",
  "Yo mama is so ugly, her portraits hang themselves.",
  "Yo momma so ugly that Ripley's doesn't believe it.",
  "Yo mamma so ugly she is the reason Waldo is hiding.",
  "Yo mama so ugly she gives Freddy Krueger nightmares.",
  "Yo mama is so ugly, even bullets refuse to kill her.",
  "Yo mama is so ugly, even Ripley wouldn't believe it.",
  "Yo mama is so ugly that she scares the roaches away.",
  "Yo mama is so ugly that her shadow ran away from her.",
  "Your momma so ugly she has to sneak up on the mirror.",
  "Your mama is so ugly even the tide won't take her out.",
  "Yo mama is so ugly that people go as her for Halloween.",
  "Yo mama so ugly, she made the illuminati close its eye!",
  "Yo momma is so ugly, she makes the sun easy to look at.",
  "Yo mama so ugly the Terminator said « I won't be back ».",
  "Yo mama is so ugly that she made Barack Obama lose hope!",
  "Yo mama so ugly, she made One Direction go the other way.",
  "Yo momma is so ugly Fix-It Felix said « I can't fix it ».",
  "Yo mamma is so ugly, she scared the shit out of the toilet.",
  "Yo mama so ugly, her birth certificate is an apology letter.",
  "Yo momma is so ugly even Hello Kitty said « Goodbye » to her",
  "Yo mama is so ugly that she gives Freddy Kreuger nightmares.",
  "Yo momma is so ugly, the psychiatrist makes her lie facedown.",
  "Yo momma is so ugly, even the trash man wouldn't pick her up.",
  "Yo mama is so ugly that even Rice Krispies won't talk to her!",
  "Yo mama's so ugly, she could scare the s*** out of the toilet.",
  "Yo mamma is so ugly when she took a bath the water jumped out.",
  "Yo mama is so ugly when the devil saw her, he started praying.",
  "Yo mama is so ugly that she scared the crap out of the toilet.",
  "Your mom is so ugly, she put her make up on and it jumped off.",
  "Yo mama is so ugly, she's only allowed to go out on October 31.",
  "Yo mama is so ugly she couldn't even get a date on the calendar.",
  "Yo mama is so ugly that she'd scare the monster out of Loch Ness.",
  "Yo momma is so ugly her parents had to feed her with a slingshot.",
  "Your mom is so ugly not even Goldfish crackers smile back at her.",
  "Yo momma so ugly, that most Snapchat filters make her look better.",
  "Your momma is so ugly she made One Direction go another direction.",
  "Yo mama so ugly she slapped herself and her face slapped her back.",
  "Yo momma is so ugly she is the reason Sonic the Hedgehog runs fast.",
  "Yo mama is so ugly that she could scare the flies off a shit wagon.",
  "Yo mama is so ugly that her face is blurred on her driver's license.",
  "Yo mama's so ugly, she threw a boomerang and it refused to come back.",
  "Yo momma so ugly, when she looks in the mirror, the reflection ducks.",
  "Yo mama is so ugly, I heard that your dad first met her at the pound.",
  "Yo mama's so ugly, when she was born the doctor slapped your grandma.",
  "Yo mama so ugly that when she went to hell, the devil went to church.",
  "Yo mama so ugly Scorpion from Mortal Kombat says « Stay over there ».",
  "Yo mama is so ugly that people at the circus pay money not to see her.",
  "Yo mamma is so ugly that when Justin Bieber saw her, he said « Never ».",
  "Yo momma's so ugly, they filmed « Gorillas in the Mist » in her shower.",
  "Yo momma is so ugly, when she looks in the mirror Bloody Mary goes away.",
  "Yo mama is so ugly that we put her in the kennel when we go on vacation.",
  "Yo mama is so ugly that she could make a freight train take a dirt road.",
  "Yo mama is so ugly that neither Jacob nor Edward want her on their team.",
  "Yo mama is so ugly that she could be the poster child for birth control.",
  "Yo mama is so ugly that if she was a scarecrow, the corn would run away.",
  "Yo momma's so ugly, hotel managers use her picture to keep away the rats.",
  "Yo mama is so ugly that she tried to take a bath and the water jumped out!",
  "Yo mama is so ugly that they pay her to put her clothes on in strip joints",
  "Yo mama is so ugly that it looks like she's been bobbing for french fries.",
  "Yo mama's so ugly, she went to the toilet and it jumped out of the window.",
  "Yo mama's so ugly, when she was little, she had to trick-or-treat by phone.",
  "Yo mama is so ugly that she climbed the ugly ladder and didn't miss a step.",
  "Yo mama is so ugly when she looked into the mirror, the mirror looked away.",
  "Yo mama is so ugly, I told her to take out the trash and she left the house.",
  "Yo mama is so ugly that she practices birth control by leaving the lights on.",
  "Yo mama is so ugly that she threw a boomerang and it wouldn't even come back.",
  "Yo mama is so ugly that Santa pays an elf to drop off her gifts at Christmas.",
  "Yo mama is so ugly that they push her face into dough to make gorilla cookies.",
  "Yo mama so ugly when she went to the bank they asked her to put on a ski mask.",
  "Yo mamas so ugly Wreck-it-Ralph said « No one can wreck that thing any worse »",
  "Yo mama is so ugly that when I last saw a mouth like hers, it had a hook in it.",
  "Yo momma so ugly when she saw her reflection in the mirror, it said « I quit ».",
  "Yo mama was such an ugly baby that her parents had to feed her with a slingshot.",
  "Yo momma so ugly she is the reason they turn off the lights at the movie theater.",
  "Yo momma's so cross-eyed, she went to a movie and thought it was a double feature.",
  "Yo mama is so ugly that she's never seen herself 'cause the mirrors keep breaking.",
  "Yo mama so ugly, her parents flipped a coin to see who had to kiss her good night.",
  "Yo mama is so ugly that it looks like someone did the stanky leg dance on her face.",
  "Yo mama is so ugly, they didn't give her a costume when she tried out for Star Wars.",
  "Yo mama is so ugly, when your dad drops her off for work, he gets a fine for littering.",
  "Yo mama's so ugly, when Wreck - It - Ralph saw her face he said « it's already broken »",
  "Yo momma's so ugly, they knew what time she was born because her face stopped the clock.",
  "Yo mama is so ugly that when she went to a beautician it took 12 hours... to get a quote!",
  "Yo momma's so ugly that your birth certificate was an apology letter from the Trojan man.",
  "Yo mama is so ugly that that when she sits in the sand on the beach, cats try to bury her.",
  "Yo mama is so ugly that when she was born she was put in an incubator with tinted windows.",
  "Yo momma's so ugly, they push her face into the dough mixture when making monster cookies.",
  "Yo momma's so ugly, we had to tie a steak around her neck so the dogs would play with her.",
  "Yo mama is so ugly that when she walks into a bank, they turn off the surveillence cameras.",
  "Yo momma is so ugly that when the Kool-Aid man broke through her wall he said « Oh noooo »!",
  "Yo mama's so ugly, your dad takes her to work so he doesn't have to give her a kiss goodbye.",
  "Yo momma is so ugly her momma had to tie a steak around her neck to get the dog to lick her.",
  "Yo momma is so ugly that when she walked into Wal-Mart they turned off the security cameras.",
  "Yo momma's so ugly, in September, folk say « Damn it, can't believe it's Halloween already ».",
  "Yo mama is so ugly that you have to tie a steak around her neck so the dog will play with her!",
  "Yo mama is so ugly that when she plays Mortal Kombat, Scorpion tells her to 'Stay Over There!'",
  "Yo mama is so ugly that she has 7 years bad luck just trying to look at herself in the mirror.",
  "Yo momma so ugly that if ugliness was measured in bricks she would be the Great Wall of China.",
  "Yo mamma so ugly, she came in fourth at a beauty pageant and she was the only one who entered.",
  "Yo mama is so ugly, she walked into a haunted house and walked back out with a job application.",
  "Yo mama is so ugly that when she walked out of her house, the neighbours called animal control.",
  "Yo mama is so ugly that people hang her picture in their cars so their radios don't get stolen.",
  "Yo mama is so ugly that when she goes to the therapist, he makes her lie on the couch face down.",
  "Yo momma is so ugly she didn't get hit with just the ugly stick; she got hit with the whole tree.",
  "Yo' Mama is so ugly, yo' daddy takes her to work with him so he doesn't have to kiss her goodbye.",
  "Yo mama is so ugly that the last time I saw something that looked like her, I pinned a tail on it.",
  "Yo mama so ugly she looked in the mirror and the mirror said « Hell no, I ain't reflecting that »!",
  "Yo momma's so ugly, they put her in the chimp enclosure to stop the chimpanzee's from jerking off!",
  "Yo mama is so ugly, people convinced her that it was Halloween every day so she would wear a mask.",
  "Yo mama is so ugly that a sculpture of her face is used when torturing prisoners at Guantanamo Bay.",
  "Yo momma's so ugly, instead of around the ankles, they put the bungee jumping cord around her neck.",
  "Yo mama so ugly when she went to the zoo they had to shut it down because there was a « loose bear »",
  "Yo mama is so ugly that when she moved into the projects, all her neighbors chipped in for curtains.",
  "Yo mama is so ugly that government intelligence agencies have to pixelize her face when spying on her.",
  "Yo mama is so ugly that when she walks in the kitchen, the rats jump on the table and start screaming.",
  "Yo mamma's so ugly, when her house was being robbed, the mugger took off his mask and made her wear it.",
  "Yo momma's so ugly, George Lucas cast her in Star Wars 3 as Jabba's wife, without the need for a costume.",
  "Yo mama is so ugly that the FCC requires her face to be blurred when she's on TV, because of decency rules.",
  "Yo mama is so ugly that when she walks down the street in September, people say 'Wow, is it Halloween already?'",
  "Yo mama is so ugly that that your father takes her to work with him so that he doesn't have to kiss her goodbye.",
  "Yo mom is so ugly, when she robbed a bank the workers gave her the money in the bank to just not see her face anymore!",
  "Yo mama is so ugly that when she uploaded a photo of herself to a computer, it was rejected by the anti-virus software.",
  "Yo momma so ugly that when she played Mortal Kombat instead of Scorpion saying « Get over here »! He said « Stay over there »!",
  "Yo mamma so ugly when she was born your grandmamma said « What a treasure », and your granddaddy said « Yeah, let's go bury it ».",
  "Yo mama is so ugly that when she drove past area 51, she was thought to be extraterrestrial life. They took her away never to be seen again.",
  "Yo mamma is so ugly, when she brought a pig into Walmart, the manager said « Get that pig out of here », and the pig said « Sorry, it won't happen again »!",
  "Yo mama's so ugly, Sonic.exe doesn't want to play with her. Yo mama's so ugly, her mirror says « VIEWER DISCRETION IS ADVISED ». Yo mama's so ugly, Unwanted House Guest doesn't go to her house.",
  "Yo momma's so ugly, she made an onion cry.",
  "Yo momma so ugly her pillow cries at night!",
  "Yo momma is so ugly she turned Medusa into stone.",
  "Yo momma's so ugly, the government moved Halloween to her birthday!",
  "Yo momma's so ugly, she gets 364 extra days to dress up for Halloween.",
  "Yo mama is so ugly, she looked out the window and got arrested for mooning.",
  "Yo mama's so ugly that when she looks in the mirror it says « Viewer discretion is advised ».",
  "Yo mama so ugly, your father brings her to work so he doesn't have to kiss her goodbye.",
  "Your mama is so ugly, when she went in a haunted house, she came out with a job application",
  "Yo momma’s so ugly, when they took her to the beautician it took 12 hours – for a quote!",
  "Yo mamma is so ugly when she tried to join an ugly contest they said « Sorry, no professionals ».",
  "Yo mama is so ugly that just after she was born, her mother said 'What a treasure!' and her father said 'Yes, let's go bury it.'",
  "Yo mama's so ugly, she gets trick-or-treaters in July.",
  "Yo mama so ugly, her smartphone's Face ID requires a CAPTCHA just to prove it's looking at a human.",
  "Yo mama so ugly, even Face ID shuts its eyes and asks for the passcode.",
  "Your mother walked into a funhouse mirror maze, and the mirrors actually straightened themselves out just to avoid making things any worse.",
  "Ya mama so ugly, she walked into a modern art gallery and won first prize for 'Bold Depiction of Chaos'.",
  "Ya mama so ugly, she walked into a modern art gallery and the curator tried to hang her on the wall.",
  "Yer ma's so ugly, when she walks into the forest, the trees start shedding their leaves early just to cover her up.",
  "Your mom is so ugly, when she tried to use FaceID, her phone redirected her to a CAPTCHA page just to prove she was human.",
];
